using CRM.Domain.Enums;

namespace CRM.API;

/// <summary>Canonical Games Library seed rows, transcribed from the Annual Programming Calendar spreadsheet.</summary>
public record GameSeedRow(
    string Name,
    GameSource Source,
    GameCategory Category,
    string? CategoryLabel,
    GameTier Tiers,
    string AreaSlug,
    (string SubSkillSlug, bool IsPrimary)[] SubGoals,
    string? Description,
    string? BestFor,
    string? WhenToUse);

public static class GameSeedData
{
    public static readonly GameSeedRow[] Games = new GameSeedRow[]
    {
        // WARMUPS & ACTIVITIES
        new("Tongue Twisters", GameSource.TSSP, GameCategory.Warmup, "Vocal Warmup", GameTier.All, "communication",
            new (string, bool)[] { ("verbal-communication", true), ("script-reading-memorization", false) },
            "Articulation drills. 20+ in vault: Red leather; Sally sells seashells; Peter Piper; Toy boat (x3).",
            "Articulation, diction, playfulness",
            "Top of every session"),
        new("Emotion Check-in", GameSource.TSSP, GameCategory.Warmup, "Circle / Ritual", GameTier.All, "social",
            new (string, bool)[] { ("emotional-regulation-empathy", true), ("perspective-taking-adaptability", false) },
            "Circle check-in. Stars choose first animal/color/shape. Always invite, respect privacy.",
            "Acting → Animals · Singing → Colors · Dancing → Shapes",
            "Opening circle"),
        new("1-2-1 Vocal Warm-Up Scales", GameSource.TSSP, GameCategory.Warmup, "Vocal", GameTier.All, "performing-arts",
            new (string, bool)[] { ("musical-vocal-training", true), ("verbal-communication", false) },
            "Ascending/descending scale: 1, 1-2-1 up to 1-2-3-4-5-6-7-8-7-6-5-4-3-2-1.",
            "Pitch, range, breath control",
            "Vocal class / pre-show warm-up"),
        new("Snowman Vocal Warm-Up", GameSource.TSSP, GameCategory.Warmup, "Vocal", GameTier.All, "performing-arts",
            new (string, bool)[] { ("musical-vocal-training", true) },
            "Break vocal range into 3 parts. Slide between three points.",
            "Range exploration, vocal health",
            "Vocal warm-up"),
        new("Breathe Like the Ocean", GameSource.TSSP, GameCategory.Warmup, "Meditation", GameTier.All, "social",
            new (string, bool)[] { ("emotional-regulation-empathy", true) },
            "Guided breathing meditation (Moana-inspired).",
            "Centering, breath, calm",
            "Pre-performance, cool-down"),
        new("Actor Suit", GameSource.TSSP, GameCategory.Warmup, "Grounding / Theater", GameTier.All, "multi-area",
            new (string, bool)[] { ("acting", true), ("attention-and-focus", false), ("following-a-schedule", false) },
            "Step-by-step neutral skeletal posture: feet, ankles, knees, hips, ribs, chin, arms relaxed.",
            "Foundational: builds from fresh start",
            "Beginning of acting work, reset"),
        new("123 Focus Activity", GameSource.TSSP, GameCategory.Warmup, "Ensemble", GameTier.Novice | GameTier.Intermediate, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true), ("group-collaboration", false) },
            "Count to 3 in circle. Replace #1 with clap, #2 with jump, #3 with word.",
            "Focus, coordination, memory",
            "Quick reset"),
        // CIRCLE GAMES
        new("Pass the Pulse / Clap", GameSource.TSSP, GameCategory.Circle, "Circle / Ensemble", GameTier.All, "social",
            new (string, bool)[] { ("group-collaboration", true), ("attention-and-focus", false) },
            "Standing/sitting circle. Eye contact + simultaneous clap to pass pulse.",
            "Variations: outs for missed; shoulder tap",
            "Warm-up, focus reset"),
        new("Story Circle", GameSource.TSSP, GameCategory.Circle, "Theater / Ensemble", GameTier.All, "communication",
            new (string, bool)[] { ("verbal-communication", true), ("group-collaboration", false) },
            "Group builds a story one sentence at a time on a chosen theme.",
            "Five Minute Fairytale; Headline",
            "Pre-devising"),
        new("Big Booty", GameSource.TSSP, GameCategory.Circle, "Rhythm / Ensemble", GameTier.Intermediate | GameTier.Expert, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true), ("group-collaboration", false) },
            "Numbered group rhythm game. Off rhythm = out and shift numbers.",
            "No Callbacks; No Chronology",
            "Energy + memory"),
        new("Hands (Pulse Squeeze)", GameSource.TSSP, GameCategory.Circle, "Circle / Ensemble", GameTier.All, "social",
            new (string, bool)[] { ("group-collaboration", true), ("non-verbal-communication", false) },
            "Circle joined hands. Squeeze pulse races invisibly.",
            "Different directions, speeds",
            "Listening, trust"),
        new("Bippity Bippity Bop", GameSource.TSSP, GameCategory.Circle, "Ensemble / Movement", GameTier.Novice | GameTier.Intermediate, "multi-area",
            new (string, bool)[] { ("attention-and-focus", true), ("group-collaboration", false), ("acting", false) },
            "Spinner points, yells 'Bippity Bippity Bop'. Target makes elephant; neighbors make ears.",
            "Silent counting + bunny (sound-sensitive)",
            "Energy spike, play"),
        new("Group Counting", GameSource.TSSP, GameCategory.Circle, "Ensemble", GameTier.Novice | GameTier.Intermediate, "social",
            new (string, bool)[] { ("group-collaboration", true), ("attention-and-focus", false) },
            "Count to 10 without speaking over each other. Restart if overlap.",
            "Song lyrics version",
            "Reset, listening"),
        new("Musical Dots (8 and under)", GameSource.TSSP, GameCategory.Circle, "Dance / Movement", GameTier.Novice, "multi-area",
            new (string, bool)[] { ("group-collaboration", true), ("dance-movement", false), ("transitions", false) },
            "Dots on floor; dance pose on dot when music stops. Remove dots gradually.",
            "Best for younger Stars",
            "Dance class"),
        new("Find a Chair / Dot", GameSource.TSSP, GameCategory.Circle, "Icebreaker / Circle", GameTier.Novice | GameTier.Intermediate, "social",
            new (string, bool)[] { ("group-collaboration", true), ("public-interaction", false) },
            "'Find a chair if you...'. Can't return to same/adjacent chair.",
            "Find a dot for smaller spaces",
            "Icebreaker for new students"),
        new("Clap Focus", GameSource.TSSP, GameCategory.Circle, "Ensemble", GameTier.Intermediate | GameTier.Expert, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true) },
            "Clap at random person; they clap at someone else. Continuous clap effect.",
            "Distractions, eye-contact-only, silent",
            "Focus, response time"),
        new("Zip Zap Zop (Easy)", GameSource.TSSP, GameCategory.Circle, "Ensemble", GameTier.Novice, "social",
            new (string, bool)[] { ("group-collaboration", true), ("attention-and-focus", false) },
            "Clap across circle saying zip/zap/zop in order with eye contact.",
            "Easy stays in order",
            "Classic warm-up"),
        new("Zip Zap Zop (Hard)", GameSource.TSSP, GameCategory.Circle, "Ensemble", GameTier.Intermediate | GameTier.Expert, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true), ("group-collaboration", false) },
            "Zip=right, Zap=left, Zop=across. Choose any on your turn.",
            "Spatial thinking",
            "Energy + focus reset"),
        new("Zip Zap Zop (In-Depth)", GameSource.TSSP, GameCategory.Circle, "Ensemble", GameTier.Expert, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true) },
            "Can say 'zap' to reverse direction; 'zoop' to send to anyone.",
            "Most advanced",
            "Advanced ensemble"),
        new("Whoosh Ball", GameSource.TSSP, GameCategory.Circle, "Ensemble", GameTier.All, "social",
            new (string, bool)[] { ("group-collaboration", true), ("non-verbal-communication", false) },
            "Energy-matching invisible ball passes around circle. Never decrease energy.",
            "Whoosh, Bong, Bridge, Suspension Bridge, Canoeing",
            "Energy management"),
        // MOVEMENT GAMES
        new("Yes, Let's!", GameSource.TSSP, GameCategory.Movement, "Theater / Improv", GameTier.Novice | GameTier.Intermediate, "multi-area",
            new (string, bool)[] { ("group-collaboration", true), ("verbal-communication", false), ("acting", false) },
            "Mill about; 'Let's all ___'; group responds 'YES LET'S' and mimes.",
            "Acceptance, silliness",
            "Improv intro"),
        new("Charades", GameSource.TSSP, GameCategory.Movement, "Theater", GameTier.All, "performing-arts",
            new (string, bool)[] { ("non-verbal-communication", true), ("acting", false) },
            "Group or team guessing through pantomime.",
            "One-word prompts for younger Stars",
            "Reset, fun energy"),
        new("Shapes and Sizes", GameSource.TSSP, GameCategory.Movement, "Movement / Ensemble", GameTier.All, "social",
            new (string, bool)[] { ("group-collaboration", true), ("peer-collaboration-outside-class", false) },
            "'Two-person bridge', 'three-person tower', etc. Groups form shape.",
            "Encourages new partners",
            "Cooperation, mixed-age"),
        new("Animalz", GameSource.TSSP, GameCategory.Movement, "Character / Movement", GameTier.All, "performing-arts",
            new (string, bool)[] { ("acting", true), ("non-verbal-communication", false) },
            "Travel as animals without touching/interacting.",
            "Interact + improvise; full scenes as animals",
            "Character creation"),
        // NAME GAMES
        new("Show Me Your Moves! (Easy)", GameSource.TSSP, GameCategory.Name, "Name / Ensemble", GameTier.Novice, "social",
            new (string, bool)[] { ("group-collaboration", true), ("self-direction-choice-making", false) },
            "Each Star says name + action. Everyone repeats together.",
            "Easy for young Stars (5-7)",
            "First day"),
        new("Show Me Your Moves! (Hard)", GameSource.TSSP, GameCategory.Name, "Name / Ensemble", GameTier.Intermediate | GameTier.Expert, "multi-area",
            new (string, bool)[] { ("group-collaboration", true), ("self-direction-choice-making", false), ("attention-and-focus", false) },
            "Each Star says name + move. Next person repeats all + adds.",
            "Memory chain ~20 names",
            "First day older groups"),
        new("Zip Zap Zop (Name)", GameSource.TSSP, GameCategory.Name, "Name / Ensemble", GameTier.Novice | GameTier.Intermediate, "social",
            new (string, bool)[] { ("group-collaboration", true), ("verbal-communication", false) },
            "Zip Zap Zop with players' names swapped in.",
            "Once foundation names known",
            "Name learning"),
        new("Popsico (Pop See Ko)", GameSource.TSSP, GameCategory.Name, "Name / Dance", GameTier.All, "multi-area",
            new (string, bool)[] { ("verbal-communication", true), ("self-direction-choice-making", false), ("dance-movement", false) },
            "Call-and-response song. Each Star picks a move that everyone imitates.",
            "Until everyone has a turn",
            "Strong opener"),
        // ICEBREAKER GAMES
        new("Fuzzy Wuzzy", GameSource.TSSP, GameCategory.Icebreaker, "Icebreaker", GameTier.All, "social",
            new (string, bool)[] { ("group-collaboration", true), ("emotional-regulation-empathy", false) },
            "'Will you be my fuzzy wuzzy?' Response without smiling.",
            "Builds bonds, comfort",
            "Icebreaker, reset"),
        new("Interview (basic)", GameSource.TSSP, GameCategory.Icebreaker, "Theater", GameTier.Novice | GameTier.Intermediate, "communication",
            new (string, bool)[] { ("verbal-communication", true), ("public-interaction", false) },
            "Teacher interviewer: 'Who are you?'",
            "Character Interview, Twin Interview",
            "Introductions"),
        new("Director Says", GameSource.TSSP, GameCategory.Icebreaker, "Icebreaker / Theater", GameTier.Novice, "executive-functioning",
            new (string, bool)[] { ("following-a-schedule", true), ("attention-and-focus", false) },
            "Simon Says with stage directions.",
            "Classic listening",
            "Reset, quick energy"),
        new("Slow Motion Samurai", GameSource.TSSP, GameCategory.Icebreaker, "Movement", GameTier.Intermediate | GameTier.Expert, "multi-area",
            new (string, bool)[] { ("non-verbal-communication", true), ("transitions", false), ("attention-and-focus", false) },
            "Mill in slow motion; touch by forearm = poisoned death.",
            "Block with forearm; two teams",
            "Older Stars"),
        // THEATER GAMES
        new("Twizzle", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.All, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true), ("transitions", false) },
            "Simon Says with acting twist. Twizzle = jump, spin 360, land, FREEZE.",
            "Wiggle-break, reset",
            "Listening + body readiness"),
        new("Mirror (Double Speak)", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Intermediate | GameTier.Expert, "multi-area",
            new (string, bool)[] { ("non-verbal-communication", true), ("group-collaboration", false), ("attention-and-focus", false) },
            "Two players act as one person, one word at a time.",
            "Improv scene; twin format",
            "Listening, partnering"),
        new("Freeze", GameSource.TSSP, GameCategory.Theater, "Improv", GameTier.Intermediate, "performing-arts",
            new (string, bool)[] { ("acting", true), ("self-direction-choice-making", false) },
            "Improvised scene. Caller 'freeze' → taps member out → new scene.",
            "Classic improv staple",
            "Improv class"),
        new("Look Up and ACT!", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Novice | GameTier.Intermediate, "performing-arts",
            new (string, bool)[] { ("acting", true), ("group-collaboration", false) },
            "Look down; '1,2,3, look up'. Eye contact pairs perform action.",
            "Pre-agree the action",
            "Reset, commitment"),
        new("Meter Tag", GameSource.TSSP, GameCategory.Theater, "Movement", GameTier.Expert, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true), ("transitions", false) },
            "Metronome 1-2-3-4. Move on 1+2, tag on 3, freeze on 4.",
            "Beat + spatial awareness",
            "Advanced movement"),
        new("Character Interview", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Intermediate | GameTier.Expert, "communication",
            new (string, bool)[] { ("verbal-communication", true), ("acting", false) },
            "Interviewer + interviewees in character. 3-5 min.",
            "Twin Interview, Interview Panel",
            "Character work"),
        new("Gibberish Interpreter", GameSource.TSSP, GameCategory.Theater, "Improv", GameTier.Intermediate | GameTier.Expert, "multi-area",
            new (string, bool)[] { ("non-verbal-communication", true), ("verbal-communication", false), ("acting", false) },
            "One speaks gibberish; another interprets matching tone.",
            "Tone + intention",
            "Improv class"),
        new("Director's Coming", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Novice | GameTier.Intermediate, "executive-functioning",
            new (string, bool)[] { ("following-a-schedule", true), ("attention-and-focus", false) },
            "Simon Says with stage commands. 'Director's coming!' = attention.",
            "Trapdoor, Stage Death, Hamlet",
            "Reset, theater vocabulary"),
        new("Quick Change", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Intermediate, "executive-functioning",
            new (string, bool)[] { ("attention-and-focus", true), ("task-initiation", false) },
            "Leave room 10 sec, change 3 things. Others guess.",
            "Observation",
            "Reset, visual work"),
        new("Dinner Party", GameSource.TSSP, GameCategory.Theater, "Improv", GameTier.Intermediate | GameTier.Expert, "communication",
            new (string, bool)[] { ("verbal-communication", true), ("acting", false) },
            "Host steps out; others choose personas. Host guesses identities.",
            "3-6 guests + host",
            "Character work"),
        new("The Normal Guy", GameSource.TSSP, GameCategory.Theater, "Improv", GameTier.Intermediate | GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("acting", true), ("self-direction-choice-making", false) },
            "Each lists something odd about the other. Compete to be normal.",
            "Add third actor",
            "Improv, character logic"),
        new("1-2-3-4 (Open Scene)", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Intermediate | GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("acting", true), ("group-collaboration", false) },
            "Three-person structured exercise. P1 mimes; P2 enters; P1 conflict; P2 stakes; P3 resolves.",
            "Gibberish; offstage voiceover",
            "Open scene fundamentals"),
        new("Park Bench", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Intermediate | GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("acting", true), ("non-verbal-communication", false) },
            "Silent character on bench; new character enters; ~30 sec; rotation.",
            "Info Desk variation",
            "Character embodiment"),
        new("Help Desk", GameSource.TSSP, GameCategory.Theater, "Improv", GameTier.Intermediate | GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("acting", true), ("verbal-communication", false) },
            "One plays help desk clerk; others approach as characters.",
            "Personnel manager; Mountain guru",
            "Character + improv"),
        new("Photograph", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.All, "multi-area",
            new (string, bool)[] { ("acting", true), ("non-verbal-communication", false), ("group-collaboration", false) },
            "One freezes; others join to fill the photo. Guess what it is.",
            "Bring photo to life",
            "Ensemble + composition"),
        new("Yes And", GameSource.TSSP, GameCategory.Theater, "Improv", GameTier.All, "communication",
            new (string, bool)[] { ("verbal-communication", true), ("self-direction-choice-making", false), ("group-collaboration", false) },
            "Two-person scene. Each line begins 'YES AND...' Accept and build.",
            "'Yes But' explores stopping power of NO",
            "Improv foundation"),
        new("Silent Scene", GameSource.TSSP, GameCategory.Theater, "Theater", GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("non-verbal-communication", true), ("acting", false) },
            "Open scene with no talking. Truthful action.",
            "NOT mime/charades",
            "Advanced specificity"),
        new("Restaurant", GameSource.TSSP, GameCategory.Theater, "Improv", GameTier.Intermediate | GameTier.Expert, "communication",
            new (string, bool)[] { ("verbal-communication", true), ("acting", false) },
            "Two guests improvise 'rumor' about waitstaff. Waiter embodies it.",
            "Min 3 players",
            "Improv, comedic timing"),
        new("Machines", GameSource.TSSP, GameCategory.Theater, "Ensemble", GameTier.All, "multi-area",
            new (string, bool)[] { ("group-collaboration", true), ("non-verbal-communication", false), ("acting", false) },
            "Players add repeating action + sound to a non-existent machine.",
            "No leader; sped/slowed",
            "Group composition"),
        // RESET GAMES
        new("Jingle Bells (TK-2)", GameSource.TSSP, GameCategory.Reset, "Reset", GameTier.Novice, "social",
            new (string, bool)[] { ("emotional-regulation-empathy", true), ("attention-and-focus", false) },
            "Pass jingle bells quietly. If rung, restart.",
            "Best for youngest Stars",
            "Reset after high-energy"),
        // SUGGESTED ADDITIONS
        new("Tableau", GameSource.Suggested, GameCategory.SuggestedAddition, "Theater", GameTier.All, "performing-arts",
            new (string, bool)[] { ("acting", true), ("non-verbal-communication", false), ("group-collaboration", false) },
            "Frozen image on a prompt. Foundation for composition.",
            "Pairs with Photograph",
            "Intro to staging"),
        new("Status Cards", GameSource.Suggested, GameCategory.SuggestedAddition, "Theater", GameTier.Intermediate | GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("acting", true), ("perspective-taking-adaptability", false) },
            "Draw 1-10 card; play scene at that status.",
            "Status work",
            "Character intensive"),
        new("Hot Seat", GameSource.Suggested, GameCategory.SuggestedAddition, "Theater", GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("acting", true), ("verbal-communication", false) },
            "Star answers questions in character about backstory.",
            "Character history",
            "Pre-rehearsal"),
        new("Soundscape", GameSource.Suggested, GameCategory.SuggestedAddition, "Music / Theater", GameTier.All, "performing-arts",
            new (string, bool)[] { ("musical-vocal-training", true), ("group-collaboration", false) },
            "Group builds environmental soundscape using voice.",
            "Atmosphere, listening",
            "Pre-scene environment"),
        new("Image Theater (Boal)", GameSource.Suggested, GameCategory.SuggestedAddition, "Devising", GameTier.Intermediate | GameTier.Expert, "performing-arts",
            new (string, bool)[] { ("acting", true), ("non-verbal-communication", false), ("group-collaboration", false) },
            "Group sculpts bodies into images representing themes.",
            "Devising, social themes",
            "Themed programming"),
    };
}
